### PR TITLE
filtering response in index.js

### PR DESCRIPTION
**Pull request by nemesis1346**
I just filtered the inactive members of the list in the front end:

  console.log('RESPONSE FRONT END');
        console.log(data);
        let is_active_filter_data = data.filter(function(item){
          return item.is_active;
        });
        console.log('FILTERED ARRAY');
        console.log(is_active_filter_data);
        this.setState({ members: is_active_filter_data });
        console.log('request succeeded with JSON response', data);

The change was made in the following path:
/home/nemesis1346/Documents/workstand/bikeshop_project/assets/js/members/components/MemberTable/index.jsx

### CODE REVIEW

**Comment by foltra** [comment]
I think that what @FeXd  wanted this to be a sorted response, rather than filtered. We still want to see the inactives at the bottom.

**Comment by nemesis1346** [comment]
Do we need timestamp or date parameters in the object model for this? I didnt find any. Sorting them by date was what I was thinking on. Sorry for the misunderstanding before.

**Comment by foltra** [comment]
I'm looking at [this](https://github.com/BridgeCityBicycleCoop/workstand/issues/87#issuecomment-501480127) comment from @FeXd , that should probably be added to AC.


This could be done by responding from backend the Visit data associated  to every member and reorder in a reducer in the frontend, or do the ordering on the backend before sending. 
Could also be just an extra field with 'last_visit' instead of responding with all visit data.

**Comment by drwlrsn** [comment]
I think this is going to be a bit trickier than we imagined. Because our sign-in search field uses a secondary index. We currently index the value from `Member.get_full_name` and `Member.email` but we will now need to include some date the represents their last visit. So we can sort and filter the results before turning them.

We can add to the `Member` model a new method like
```python
    def get_sort_date_for_signin_search(self):
        try:
            return self.visit_set.latest('created_at')
        except ObjectDoesNotExist:
            return self.created_at
```

We can update our index every time the `Member` is saved
```python
class MemberIndex(indexes.SearchIndex, indexes.Indexable):
    text = indexes.EdgeNgramField(document=True, use_template=True)
    email = indexes.CharField(model_attr='email')
    full_name = indexes.CharField(model_attr='get_full_name')
    sort = indexes.DateTimeField(model_attr='get_sort_date_for_signin_search')


    def get_model(self):

        return Member
```

But we need to update our index every time a new `Visit` is created. And to be honest I am not entirely sure if Haystack knows how to listen for saves on related models.

**Pull request closed without merging**
