### PR TITLE
fail if missing migrations

### LINKED ISSUE #94: Fail CI if migration missing
We probs are looking for this: https://docs.djangoproject.com/en/1.11/ref/django-admin/#cmdoption-makemigrations-check
```
manage.py makemigrations --check 
```

### PR DESCRIPTION
**Pull request by foltra**
Fixes #94 

~script to be tested~

### CODE REVIEW

**Comment by drwlrsn** [comment]
Lol it definitely works!

**Comment by drwlrsn** [comment]
This just needs to be rebased on master and it should start passing.

**Comment by foltra** [comment]
and... passed!

**Comment by drwlrsn** [comment]
There should be only one commit and and one filed changed in this PR. It might be easier to just start a new branch, cherry pick your commit and overwrite this one.

**Comment by foltra** [comment]
rebase, oh yeah.

**Pull request merged**
